### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by ytaylordev** [Adalab/modulo-2-evaluacion-intermedia-VeroSalandy#1]
Really cool job @VeroSalandy !!!

Here you have some tips to improve the exercise:

### JavaScript: basic
- [x] Remove debugger and other unnecessary code: https://github.com/Adalab/modulo-2-evaluacion-intermedia-VeroSalandy/blob/bd0203e8c25093276068e216afaa4c3251a2d097/js/main.js#L54

### JavaScript: advanced

- [x] Check if the `<input>` has an empty value or text.
- [x] You are writing many times `"trackEl.innerHTML = 'something';"`, what about making a function that accepts a string as param and paints it into `'trackEl'`?

### JavaScript: good practices

- [x] Move variables and constants declarations to the top of the file.

### HTML

- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input.
- [x] Use placeholder attribute instead of value one to show a field's hint.

### CSS

- [x] Avoid adding styles until the js code is solid as a rock.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by VeroSalandy** [comment]
Hi @ytaylordev, I have modified all the issues/improvements, can i close this isssue or will you do it after verifying them? 
Thank you in advance :)

**Comment by ytaylordev** [comment]
Good job!
